services:
  - type: web
    name: season-reservas
    env: python
    plan: free
    buildCommand: pip install -r requirements.txt && python init_db.py
    startCommand: gunicorn --worker-class eventlet -w 1 app:app
    envVars:
      - key: FLASK_ENV
        value: production
      - key: SECRET_KEY
        sync: false
      - key: WHATSAPP_NUMBER
        value: "689135630"
